name: Update Wisdom Database

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC
  workflow_dispatch: # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py
        env:
          MAX_QUOTES: 50 # Limit number of quotes per source
          REQUEST_DELAY: 3 # Seconds between requests

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto-update wisdom quotes'
          branch: main
          file_pattern: 'quotes/*.json'
          commit_user_name: 'Wisdom Bot'
          commit_user_email: 'wisdom-bot@users.noreply.github.com'
